# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'macOS (macOS)' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for macOS (macOS)
  pod 'mpp_sample', :path => '../mpp-sample'
end
