name: CI

on: [pull_request]

jobs:
  build:
    # macOS runner so that the iOS/macOS/watchOS/tvOS simulator tests can run
    runs-on: macos-latest
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v4
      - name: Cache gradle
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.konan
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle', '**/*.gradle.kts') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
      - name: "Setup Java"
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      # Runs the tests of all targets:
      # jvm, android(host), js, wasmJs, ios, macos, watchos, tvos
      - name: Run all tests
        run: ./gradlew :napier:allTests --stacktrace

      - name: Bundle the build report
        if: failure()
        run: find . -type d -name 'reports' | zip -@ -r build-reports.zip
      - name: Upload the build report
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: error-report
          path: build-reports.zip
